### ISSUE TITLE
Cryptic error message.

### ISSUE THREAD

**Issue by rtrger** [TombRunners/autosplitters#36]
Happens when one of the components are active and LiveSplit is quit.

![image](https://user-images.githubusercontent.com/50000645/148013636-597ca768-d81d-4b29-ba90-a11845fe9102.png)

**Comment by MidgeOnGithub** [comment]
I tried replicating this error message by closing LiveSplit "normally" and by using Task Manager to end the LiveSplit process. Neither produce this result for TR123, TR2 (`ClassicComponent`-based), nor TR4 (`LaterClassicComponent`-based).
I assume this is is no longer applicable, perhaps due to a LiveSplit update or from code updates since this issue opened.
